name: website_flutter
description: "A new Flutter project."

publish_to: 'none' # This line prevents accidental publication to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cupertino_icons: ^1.0.6
  slide_countdown: ^2.0.0
  shared_preferences: ^2.3.2
  audioplayers: ^0.19.1
  just_audio: ^0.9.42

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

